export const LOCALE_MAP = { de: 'de-DE', en: 'en-US', it: 'it-IT', fr: 'fr-FR', es: 'es-ES' };

export const TRANSLATIONS = {
  de: {
    nav_shots:'Shots', nav_live:'Live', nav_analytics:'Statistiken', nav_library:'Bibliothek',
    sort_newest:'Neueste', sort_score:'Score', sort_rating:'Bewertung', sort_duration:'Dauer',
    search_placeholder:'Profil, Kaffee, Mühle …', trash_label:'Papierkorb',
    no_sync:'kein Sync', btn_sync:'↻ Sync',
    empty_title:'Keine Shots vorhanden',
    empty_desc:'Stelle sicher, dass die Gaggiuino-Maschine unter der konfigurierten URL erreichbar ist und nutze ↻ Sync.',
    loading:'Lade Shots …', btn_reload:'↻ Neu laden',
    meta_profile:'Profil', meta_pressure:'Druck (Ø / Max Ziel)', meta_flow:'Pumpenfluss (Ø / Ziel)',
    meta_temp:'Temperatur (Ø ±σ / Ziel)', meta_phases:'Phasen',
    meta_weight:'Gewicht (Gesamt / Fluss Ende)', meta_weight_flow:'Gewichtsfluss (Ø / Max)',
    meta_duration:'Dauer', meta_ratio:'Dosis → Yield · Ratio', meta_ey:'Extraction Yield (EY)',
    tab_time:'⏱ Zeit', tab_pq:'P·Q Kurve',
    btn_fullscreen_close:'✕ Schließen', btn_fullscreen_tooltip:'Vollbild',
    btn_compare_tooltip:'Als Vergleichs-Shot wählen', btn_delete_tooltip:'Shot löschen',
    ann_title:'Notizen & Bewertung',    ann_coffee:'Kaffee / Bohne', ann_coffee_ph:'z.B. Ethiopia Yirgacheffe',
    ann_grinder:'Mühle', ann_grinder_ph:'z.B. Niche Zero',
    ann_grind_setting:'Mahlgrad', ann_grind_ph:'z.B. 23 Clicks',
    ann_dose:'Dosis (g)', ann_dose_ph:'z.B. 18',
    ann_roast_date:'Röstdatum', ann_roast_date_ph:'TT.MM.JJJJ',
    ann_tds:'TDS %', ann_tds_optional:'(optional)',
    ann_tds_ph:'z.B. 9.2', ann_notes:'Notizen',
    ann_notes_ph:'Geschmack, Beobachtungen, Anpassungen …',
    ann_drink_type:'Getränk', ann_drink_type_none:'— keines —',
    btn_save:'Speichern', btn_saved:'✓ Gespeichert',
    grind_finer_urgent:'Feiner mahlen', grind_finer:'Leicht feiner mahlen',
    grind_ok:'Mahlgrad passt', grind_coarser:'Leicht gröber mahlen',
    grind_coarser_urgent:'Gröber mahlen', grind_channeling:'Puck-Vorbereitung prüfen',
    live_title:'Live Shot', live_connecting:'Verbinde …', live_brewing:'Brewing …',
    live_waiting:'Warte auf Bezug …', live_disabled:'Live deaktiviert (Maschine aus)',
    ref_label:'Referenz:', ref_none:'— kein Referenz-Shot —', ref_clear:'✕ Löschen',
    ref_pressure:'Ref: Druck', ref_flow:'Ref: Fluss', ref_weight:'Ref: Gewicht', ref_temp:'Ref: Temp',
    live_idle_text:'Sobald ein Bezug startet, erscheinen hier die Echtzeit-Daten.',
    live_time_unit:'min:sec', live_time_label:'Zeit',
    live_pressure_label:'Druck', live_flow_label:'Pumpenfluss',
    live_weight_label:'Gewicht', live_temp_label:'Temperatur',
    lib_beans:'Bohnen', lib_grinders:'Mühlen',
    lib_add_bean:'+ Bohne hinzufügen', lib_add_grinder:'+ Mühle hinzufügen',
    lib_bean_name:'Name *', lib_bean_roaster:'Rösterei', lib_bean_roast_date:'Röstdatum', lib_bean_notes:'Notizen',
    lib_grinder_name:'Name *', lib_grinder_notes:'Notizen',
    lib_bean_name_ph:'Ethiopia Yirgacheffe', lib_bean_roaster_ph:'Quijote Kaffee',
    lib_grinder_name_ph:'Niche Zero', lib_grinder_notes_ph:'Espresso: 23 Clicks',
    lib_cancel:'Abbrechen', lib_save:'Speichern',
    lib_empty_beans:'Noch keine Bohnen gespeichert', lib_empty_grinders:'Noch keine Mühlen gespeichert',
    lib_btn_edit:'Bearbeiten', lib_btn_delete:'Löschen',
    lib_confirm_delete_bean:'Bohne aus der Bibliothek löschen?',
    lib_confirm_delete_grinder:'Mühle aus der Bibliothek löschen?',
    analytics_trend:'Score-Trend', analytics_trend_30:'30 Shots', analytics_trend_90:'90 Shots', analytics_trend_all:'Alle',
    analytics_calendar:'Shot-Kalender', analytics_beans:'Bohnen-Auswertung', analytics_profiles:'Profil-Performance',
    analytics_no_trend:'Nicht genug Shots mit Score für den Trend.',
    analytics_no_beans:'Noch keine Bohnen in Annotationen eingetragen.',
    analytics_no_profiles:'Keine Profil-Daten verfügbar.',
    bean_stat_shots:'Shots', bean_stat_avg:'Ø Score', bean_stat_best:'Best', bean_stat_duration:'Ø Dauer',
    confirm_trash:'Shot in den Papierkorb verschieben?',
    confirm_delete:(id,name,date)=>`Shot ${id} löschen?\n${name} · ${date}\n\nDieser Vorgang kann nicht rückgängig gemacht werden.`,
    confirm_perm_delete:(id)=>`Shot ${id} jetzt permanent löschen?\nDieser Vorgang kann nicht rückgängig gemacht werden.`,
    trash_days_left:(d)=>`wird in ${d} Tag${d!==1?'en':''} gelöscht`,
    trash_restore_label:'↩ Wiederherstellen', trash_delete_title:'Jetzt löschen',
    freshness_title:(d)=>`${d} Tage seit Röstung (Optimum: 7–21 Tage)`,
    phase_preinfusion:'Preinfusion', phase_extraction:'Extraktion',
    grind_short:(s)=>`Bezug zu kurz (${s} s) – feiner mahlen`,
    grind_short_slight:(s)=>`Bezug etwas kurz (${s} s) – leicht feiner mahlen`,
    grind_long:(s)=>`Bezug zu lang (${s} s) – gröber mahlen`,
    grind_long_slight:(s)=>`Bezug etwas lang (${s} s) – leicht gröber mahlen`,
    grind_channeling_full:'Channeling erkannt – Puck-Vorbereitung (Verteilung & Tamping) prüfen',
    compare_hint:'Shot für Vergleich wählen',
    nav_settings:'⚙', settings_theme:'Theme', theme_dark:'Dark', theme_light:'Hell', settings_language:'Sprache',
    ann_clone_btn:'↩ Letzten',
    lib_bean_stock:'Vorrat (g)', lib_bean_stock_ph:'z.B. 500',
    lib_bean_decaf:'Entkoffeiniert',
    lib_inv_consumed:(n)=>`${n} g verbraucht`, lib_inv_remaining:(n)=>`${n} g übrig`, lib_inv_reorder:'Nachbestellen',
    lib_inv_total_consumed:(n)=>`${n} g gesamt verbraucht`,
    lib_inv_bags:(n)=>`${n} Packung${n!==1?'en':''}`,
    lib_new_bag:'+ Neue Packung',
    lib_new_bag_title:'Neue Packung',
    lib_new_bag_save:'Packung hinzufügen',
    lib_bag_history:'Packungsverlauf',
    lib_bag_roast_date:'Röstdatum',
    lib_bag_stock:'Anfangsgewicht (g)',
    lib_recipes:'Rezepte',
    lib_empty_recipes:'Noch keine Rezepte',
    lib_add_recipe:'+ Rezept hinzufügen',
    lib_recipe_name:'Name *',
    lib_recipe_drink_type:'Getränketyp',
    lib_recipe_dose:'Dosis (g)',
    lib_recipe_yield:'Ausbeute (g)',
    lib_recipe_time:'Zeit (s)',
    lib_recipe_profile:'Profil',
    lib_recipe_bean:'Bohne',
    lib_recipe_notes:'Notizen',
    lib_recipe_brew_method:'Brühmethode',
    lib_recipe_water_temp:'Wassertemperatur (°C)',
    lib_recipe_grind:'Mahlgrad',
    lib_recipe_steps:'Workflow-Schritte',
    lib_recipe_step_ph:'Schritt beschreiben …',
    lib_recipe_step_dur:'s',
    lib_recipe_add_step:'+ Schritt',
    lib_brew_espresso:'Espresso', lib_brew_aeropress:'AeroPress', lib_brew_v60:'V60 / Pour Over',
    lib_brew_french_press:'French Press', lib_brew_moka:'Moka Pot', lib_brew_cold_brew:'Cold Brew', lib_brew_other:'Sonstiges',
    lib_confirm_delete_recipe:'Rezept löschen?',
    nav_dialin:'Bezugslog', dialin_title:'Bezugslog',
    nav_maintenance:'Wartung',
    maint_descaling:'Entkalken', maint_backflush:'Backflush', maint_grouphead:'Gruppenköpf Service',
    maint_gaskets:'Dichtungen & Siebe', maint_waterfilter:'Wasserfilter',
    maint_due:'⚠ Fällig', maint_soon:'Bald fällig', maint_never:'Nie erledigt',
    maint_never_done:'Noch nie erledigt', maint_today:'Heute',
    maint_ago_days:(n)=>`Vor ${n} Tag${n===1?'':'en'}`,
    maint_shots_since:(n)=>`${n} Shot${n===1?'':'s'} seit letztem`,
    maint_thresh_shots:'Grenze Shots', maint_thresh_days:'Grenze Tage',
    maint_ok:'✓ OK',
    maint_done_btn:'Jetzt erledigt',
    dialin_empty:'Noch keine Shots für die Einwähl-Ansicht.',
    dialin_pressure:'Druck', dialin_duration:'Dauer', dialin_dose:'Dosis', dialin_ratio:'Ratio', dialin_yield:'EY %',
    degas_too_fresh:(d)=>`${d} Tage seit Röstung – noch zu frisch`,
    degas_almost:(d)=>`${d} Tage seit Röstung – fast bereit`,
    degas_optimal:(d)=>`${d} Tage seit Röstung – optimales Fenster`,
    degas_aging:(d)=>`${d} Tage seit Röstung – wird älter`,
    degas_old:(d)=>`${d} Tage seit Röstung – zu alt`,
    backup_title:'Backup & Restore',
    backup_desc:'Alle Shots, Notizen und die Kaffee-Bibliothek als JSON-Datei sichern oder wiederherstellen.',
    backup_download:'Backup herunterladen', backup_restore:'Backup wiederherstellen', backup_close:'Schließen',
    backup_confirm:'Alle aktuellen Daten werden überschrieben. Fortfahren?',
    backup_invalid:'Ungültige Backup-Datei.',
    backup_restored:(n)=>`Wiederhergestellt: ${n} Shots.`,
    backup_error:(msg)=>`Fehler: ${msg}`,
    preheat_warming:'Aufheizen …', preheat_ready:'Brühbereit ☕',
    preheat_remain:(m,s)=>`${m}:${String(s).padStart(2,'0')} verbleibend`,
    btn_export_profile_tooltip:'Gaggiuino-Profil aus Shot exportieren',
    profile_export_no_data:'Keine Profildaten in diesem Shot vorhanden.',
    sidebar_hint:'Klicke auf den Namen für Shot A. Nutze <b>⇄</b> für den Vergleich (Shot B).',
    sidebar_collapse:'Sidebar einklappen', sidebar_expand:'Sidebar aufklappen',
    error_delete:(msg)=>`Fehler beim Löschen: ${msg}`,
    error_generic:(msg)=>`Fehler: ${msg}`,
    error_load:'Fehler beim Laden',
    live_ready_status:'Bereit', live_error_status:'Fehler',
    maint_by_shots:'Shots', maint_by_days:'Tage',
    maint_grinder_section:'Mühlen',
    lib_scan_barcode:'⬛ Scan',
    lib_url_import:'🔗 URL',
    lib_url_placeholder:'kaffeebraun.com/…',
    lib_url_btn:'Importieren',
    lib_url_importing:'Importiere …',
    lib_url_error:'Fehler beim Importieren',
    lib_url_unsupported:'Nicht unterstützte Website',
    lib_imported_from:(src,date)=>`Importiert von ${src} · ${date}`,
    scan_title:'Barcode / QR scannen',
    scan_attribution:'Produktdaten von',
    scan_close:'Schließen',
    scan_searching:'Suche …',
    scan_not_supported:'Barcode-Scanner wird von diesem Browser nicht unterstützt',
    scan_not_found:'Kein Eintrag gefunden — Felder manuell ausfüllen',
    scan_found:(name)=>`Gefunden: ${name}`,
    scan_error:'Scan-Fehler — bitte erneut versuchen',
    scan_glp_imported:'GLP-QR importiert',
    bean_qr_label:'QR-Code für diese Bohne',
    nav_orders:'Bestellungen',
    orders_queue:'Warteschlange', orders_inprogress:'In Zubereitung', orders_history:'Verlauf',
    orders_empty:'Keine offenen Bestellungen',
    orders_accept:'Annehmen', orders_decline:'Ablehnen', orders_complete:'✓ Erledigt',
    orders_eta_label:'ETA (min)', orders_decline_ph:'Grund …',
    orders_machine_off:'Maschine aus – Bestellungen nicht verfügbar',
    orders_accept_toggle:'Bestellannahme', orders_accept_on:'aktiv', orders_accept_off:'pausiert',
    orders_stats_title:'Kunden-Statistik', orders_stats_total:'Gesamt', orders_stats_fav:'Lieblingsgetränk', orders_stats_last:'Zuletzt', orders_stats_orders:'Bestellungen', orders_stats_popular:'Beliebtestes Getränk', orders_stats_no_data:'Noch keine Daten',
    orders_menu_title:'Menü verwalten', orders_menu_add:'+ Getränk hinzufügen',
    orders_menu_name_ph:'Name …', orders_menu_emoji_ph:'☕', orders_menu_save:'Hinzufügen',
    orders_for:'für', orders_note_ph:'Notiz …',
    orders_ago:(m)=>`Vor ${m} Min`, orders_eta_in:(m)=>`Fertig in ${m} Min`,
    orders_declined:'Abgelehnt', orders_done:'Erledigt', orders_new_badge:'NEU',
    orders_confirm_delete_item:'Getränk aus dem Menü entfernen?',
    orders_delete_entry:'Eintrag löschen', orders_clear_history:'Verlauf löschen',
    orders_confirm_clear_history:'Gesamten Verlauf löschen?',
    orders_notify_title:'Push-Benachrichtigungen',
    orders_notify_desc:'Welches HA-Gerät soll bei Statusänderungen benachrichtigt werden?',
    orders_notify_no_service:'— kein Gerät —',
    orders_notify_save:'Speichern',
    orders_notify_saved:'✓ Gespeichert',
    orders_notify_no_customers:'Noch keine Kunden bekannt (es müssen zuerst Bestellungen eingehen).',
    orders_notify_no_ha:'HA-API nicht verfügbar — Benachrichtigungen nicht konfigurierbar.',
    orders_broadcast_title:'📢 Broadcast-Empfänger',
    orders_broadcast_desc:'Diese Geräte erhalten eine Nachricht wenn Bestellungen geöffnet werden.',
    orders_broadcast_save:'Speichern',
    orders_broadcast_saved:'✓ Gespeichert',
    orders_trending_toggle:'Trending ein/aus',
    ann_ordered_by:'Bestellt von',
  },
  en: {
    nav_shots:'Shots', nav_live:'Live', nav_analytics:'Analytics', nav_library:'Library',
    sort_newest:'Newest', sort_score:'Score', sort_rating:'Rating', sort_duration:'Duration',
    search_placeholder:'Profile, Coffee, Grinder …', trash_label:'Trash',
    no_sync:'no sync', btn_sync:'↻ Sync',
    empty_title:'No shots yet',
    empty_desc:'Make sure the Gaggiuino controller is reachable at the configured URL and tap ↻ Sync.',
    loading:'Loading shots …', btn_reload:'↻ Reload',
    meta_profile:'Profile', meta_pressure:'Pressure (avg / max target)', meta_flow:'Pump flow (avg / target)',
    meta_temp:'Temperature (avg ±σ / target)', meta_phases:'Phases',
    meta_weight:'Weight (total / end flow)', meta_weight_flow:'Weight flow (avg / max)',
    meta_duration:'Duration', meta_ratio:'Dose → Yield · Ratio', meta_ey:'Extraction Yield (EY)',
    tab_time:'⏱ Time', tab_pq:'P·Q Curve',
    btn_fullscreen_close:'✕ Close', btn_fullscreen_tooltip:'Fullscreen',
    btn_compare_tooltip:'Select as compare shot', btn_delete_tooltip:'Delete shot',
    ann_title:'Notes & Rating',    ann_coffee:'Coffee / Bean', ann_coffee_ph:'e.g. Ethiopia Yirgacheffe',
    ann_grinder:'Grinder', ann_grinder_ph:'e.g. Niche Zero',
    ann_grind_setting:'Grind setting', ann_grind_ph:'e.g. 23 Clicks',
    ann_dose:'Dose (g)', ann_dose_ph:'e.g. 18',
    ann_roast_date:'Roast date', ann_roast_date_ph:'DD.MM.YYYY',
    ann_tds:'TDS %', ann_tds_optional:'(optional)',
    ann_tds_ph:'e.g. 9.2', ann_notes:'Notes',
    ann_notes_ph:'Taste, observations, adjustments …',
    ann_drink_type:'Drink', ann_drink_type_none:'— none —',
    btn_save:'Save', btn_saved:'✓ Saved',
    grind_finer_urgent:'Grind finer', grind_finer:'Grind slightly finer',
    grind_ok:'Grind setting is good', grind_coarser:'Grind slightly coarser',
    grind_coarser_urgent:'Grind coarser', grind_channeling:'Check puck prep',
    live_title:'Live Shot', live_connecting:'Connecting …', live_brewing:'Brewing …',
    live_waiting:'Waiting for shot …', live_disabled:'Live disabled (machine off)',
    ref_label:'Reference:', ref_none:'— no reference shot —', ref_clear:'✕ Clear',
    ref_pressure:'Ref: Pressure', ref_flow:'Ref: Flow', ref_weight:'Ref: Weight', ref_temp:'Ref: Temp',
    live_idle_text:'Once a shot starts, real-time data will appear here.',
    live_time_unit:'min:sec', live_time_label:'Time',
    live_pressure_label:'Pressure', live_flow_label:'Pump Flow',
    live_weight_label:'Weight', live_temp_label:'Temperature',
    lib_beans:'Beans', lib_grinders:'Grinders',
    lib_add_bean:'+ Add bean', lib_add_grinder:'+ Add grinder',
    lib_bean_name:'Name *', lib_bean_roaster:'Roaster', lib_bean_roast_date:'Roast date', lib_bean_notes:'Notes',
    lib_grinder_name:'Name *', lib_grinder_notes:'Notes',
    lib_bean_name_ph:'Ethiopia Yirgacheffe', lib_bean_roaster_ph:'Quijote Kaffee',
    lib_grinder_name_ph:'Niche Zero', lib_grinder_notes_ph:'Espresso: 23 Clicks',
    lib_cancel:'Cancel', lib_save:'Save',
    lib_empty_beans:'No beans saved yet', lib_empty_grinders:'No grinders saved yet',
    lib_btn_edit:'Edit', lib_btn_delete:'Delete',
    lib_confirm_delete_bean:'Remove bean from library?',
    lib_confirm_delete_grinder:'Remove grinder from library?',
    analytics_trend:'Score Trend', analytics_trend_30:'30 Shots', analytics_trend_90:'90 Shots', analytics_trend_all:'All',
    analytics_calendar:'Shot Calendar', analytics_beans:'Bean Stats', analytics_profiles:'Profile Performance',
    analytics_no_trend:'Not enough scored shots for trend.',
    analytics_no_beans:'No beans entered in annotations yet.',
    analytics_no_profiles:'No profile data available.',
    bean_stat_shots:'Shots', bean_stat_avg:'Avg Score', bean_stat_best:'Best', bean_stat_duration:'Avg Duration',
    confirm_trash:'Move shot to trash?',
    confirm_delete:(id,name,date)=>`Delete shot ${id}?\n${name} · ${date}\n\nThis action cannot be undone.`,
    confirm_perm_delete:(id)=>`Permanently delete shot ${id}?\nThis action cannot be undone.`,
    trash_days_left:(d)=>`deleted in ${d} day${d!==1?'s':''}`,
    trash_restore_label:'↩ Restore', trash_delete_title:'Delete now',
    freshness_title:(d)=>`Roasted ${d} days ago (optimal: 7–21 days)`,
    phase_preinfusion:'Preinfusion', phase_extraction:'Extraction',
    grind_short:(s)=>`Shot too short (${s} s) — grind finer`,
    grind_short_slight:(s)=>`Shot slightly short (${s} s) — grind slightly finer`,
    grind_long:(s)=>`Shot too long (${s} s) — grind coarser`,
    grind_long_slight:(s)=>`Shot slightly long (${s} s) — grind slightly coarser`,
    grind_channeling_full:'Channeling detected — check puck prep (distribution & tamping)',
    compare_hint:'Select shot for comparison',
    nav_settings:'⚙', settings_theme:'Theme', theme_dark:'Dark', theme_light:'Light', settings_language:'Language',
    ann_clone_btn:'↩ Clone last',
    lib_bean_stock:'Stock (g)', lib_bean_stock_ph:'e.g. 500',
    lib_bean_decaf:'Decaffeinated',
    lib_inv_consumed:(n)=>`${n} g used`, lib_inv_remaining:(n)=>`${n} g remaining`, lib_inv_reorder:'Reorder',
    lib_inv_total_consumed:(n)=>`${n} g total used`,
    lib_inv_bags:(n)=>`${n} bag${n!==1?'s':''}`,
    lib_new_bag:'+ New bag',
    lib_new_bag_title:'New bag',
    lib_new_bag_save:'Add bag',
    lib_bag_history:'Bag history',
    lib_bag_roast_date:'Roast date',
    lib_bag_stock:'Initial weight (g)',
    lib_recipes:'Recipes',
    lib_empty_recipes:'No recipes yet',
    lib_add_recipe:'+ Add recipe',
    lib_recipe_name:'Name *',
    lib_recipe_drink_type:'Drink type',
    lib_recipe_dose:'Dose (g)',
    lib_recipe_yield:'Yield (g)',
    lib_recipe_time:'Time (s)',
    lib_recipe_profile:'Profile',
    lib_recipe_bean:'Bean',
    lib_recipe_notes:'Notes',
    lib_recipe_brew_method:'Brew method',
    lib_recipe_water_temp:'Water temperature (°C)',
    lib_recipe_grind:'Grind size',
    lib_recipe_steps:'Workflow steps',
    lib_recipe_step_ph:'Describe step …',
    lib_recipe_step_dur:'s',
    lib_recipe_add_step:'+ Step',
    lib_brew_espresso:'Espresso', lib_brew_aeropress:'AeroPress', lib_brew_v60:'V60 / Pour Over',
    lib_brew_french_press:'French Press', lib_brew_moka:'Moka Pot', lib_brew_cold_brew:'Cold Brew', lib_brew_other:'Other',
    lib_confirm_delete_recipe:'Delete recipe?',
    nav_dialin:'Dial-In', dialin_title:'Dial-In',
    nav_maintenance:'Maintenance',
    maint_descaling:'Descaling', maint_backflush:'Backflush', maint_grouphead:'Group Head Service',
    maint_gaskets:'Gaskets & Screens', maint_waterfilter:'Water Filter',
    maint_due:'⚠ Due', maint_soon:'Due soon', maint_never:'Never done',
    maint_never_done:'Never done', maint_today:'Today',
    maint_ago_days:(n)=>`${n} day${n===1?'':'s'} ago`,
    maint_shots_since:(n)=>`${n} shot${n===1?'':'s'} since last`,
    maint_thresh_shots:'Threshold shots', maint_thresh_days:'Threshold days',
    maint_ok:'✓ OK',
    maint_done_btn:'Mark as done',
    dialin_empty:'No shots yet for dial-in view.',
    dialin_pressure:'Pressure', dialin_duration:'Duration', dialin_dose:'Dose', dialin_ratio:'Ratio', dialin_yield:'EY %',
    degas_too_fresh:(d)=>`${d} days since roast — still too fresh`,
    degas_almost:(d)=>`${d} days since roast — almost ready`,
    degas_optimal:(d)=>`${d} days since roast — optimal window`,
    degas_aging:(d)=>`${d} days since roast — aging`,
    degas_old:(d)=>`${d} days since roast — too old`,
    backup_title:'Backup & Restore',
    backup_desc:'Save or restore all shots, notes and the coffee library as a JSON file.',
    backup_download:'Download backup', backup_restore:'Restore backup', backup_close:'Close',
    backup_confirm:'All current data will be overwritten. Continue?',
    backup_invalid:'Invalid backup file.',
    backup_restored:(n)=>`Restored: ${n} shots.`,
    backup_error:(msg)=>`Error: ${msg}`,
    preheat_warming:'Warming up …', preheat_ready:'Ready to brew ☕',
    preheat_remain:(m,s)=>`${m}:${String(s).padStart(2,'0')} remaining`,
    btn_export_profile_tooltip:'Export Gaggiuino profile from shot',
    profile_export_no_data:'No profile data available in this shot.',
    sidebar_hint:'Click the name for Shot A. Use <b>⇄</b> to set the compare shot (Shot B).',
    sidebar_collapse:'Collapse sidebar', sidebar_expand:'Expand sidebar',
    error_delete:(msg)=>`Delete error: ${msg}`,
    error_generic:(msg)=>`Error: ${msg}`,
    error_load:'Error loading data',
    live_ready_status:'Ready', live_error_status:'Error',
    maint_by_shots:'Shots', maint_by_days:'Days',
    maint_grinder_section:'Grinders',
    lib_scan_barcode:'⬛ Scan',
    lib_url_import:'🔗 URL',
    lib_url_placeholder:'kaffeebraun.com/…',
    lib_url_btn:'Import',
    lib_url_importing:'Importing …',
    lib_url_error:'Import failed',
    lib_url_unsupported:'Unsupported website',
    lib_imported_from:(src,date)=>`Imported from ${src} · ${date}`,
    scan_title:'Scan Barcode / QR',
    scan_attribution:'Product data from',
    scan_close:'Close',
    scan_searching:'Searching …',
    scan_not_supported:'Barcode scanning is not supported by this browser',
    scan_not_found:'No entry found — fill in fields manually',
    scan_found:(name)=>`Found: ${name}`,
    scan_error:'Scan error — please try again',
    scan_glp_imported:'GLP QR imported',
    bean_qr_label:'QR code for this bean',
    nav_orders:'Orders',
    orders_queue:'Queue', orders_inprogress:'In Progress', orders_history:'History',
    orders_empty:'No open orders',
    orders_accept:'Accept', orders_decline:'Decline', orders_complete:'✓ Done',
    orders_eta_label:'ETA (min)', orders_decline_ph:'Reason …',
    orders_machine_off:'Machine off — ordering not available',
    orders_accept_toggle:'Order acceptance', orders_accept_on:'active', orders_accept_off:'paused',
    orders_stats_title:'Customer Statistics', orders_stats_total:'Total', orders_stats_fav:'Favourite', orders_stats_last:'Last order', orders_stats_orders:'orders', orders_stats_popular:'Most popular', orders_stats_no_data:'No data yet',
    orders_menu_title:'Manage Menu', orders_menu_add:'+ Add drink',
    orders_menu_name_ph:'Name …', orders_menu_emoji_ph:'☕', orders_menu_save:'Add',
    orders_for:'for', orders_note_ph:'Note …',
    orders_ago:(m)=>`${m} min ago`, orders_eta_in:(m)=>`Ready in ${m} min`,
    orders_declined:'Declined', orders_done:'Done', orders_new_badge:'NEW',
    orders_confirm_delete_item:'Remove drink from menu?',
    orders_delete_entry:'Delete entry', orders_clear_history:'Clear history',
    orders_confirm_clear_history:'Delete entire history?',
    orders_notify_title:'Push Notifications',
    orders_notify_desc:'Which HA device should be notified on order status changes?',
    orders_notify_no_service:'— no device —',
    orders_notify_save:'Save',
    orders_notify_saved:'✓ Saved',
    orders_notify_no_customers:'No customers yet (orders must come in first).',
    orders_notify_no_ha:'HA API unavailable — notifications cannot be configured.',
    orders_broadcast_title:'📢 Broadcast recipients',
    orders_broadcast_desc:'These devices receive a notification when orders are opened.',
    orders_broadcast_save:'Save',
    orders_broadcast_saved:'✓ Saved',
    orders_trending_toggle:'Toggle trending',
    ann_ordered_by:'Ordered by',
  },
  it: {
    nav_shots:'Shots', nav_live:'Live', nav_analytics:'Statistiche', nav_library:'Libreria',
    sort_newest:'Recenti', sort_score:'Score', sort_rating:'Voto', sort_duration:'Durata',
    search_placeholder:'Profilo, Caffè, Macinino …', trash_label:'Cestino',
    no_sync:'nessun sync', btn_sync:'↻ Sync',
    empty_title:'Nessun shot',
    empty_desc:"Assicurati che il controller Gaggiuino sia raggiungibile all'URL configurato e premi ↻ Sync.",
    loading:'Caricamento shots …', btn_reload:'↻ Ricarica',
    meta_profile:'Profilo', meta_pressure:'Pressione (med / max target)', meta_flow:'Flusso pompa (med / target)',
    meta_temp:'Temperatura (med ±σ / target)', meta_phases:'Fasi',
    meta_weight:'Peso (totale / fine flusso)', meta_weight_flow:'Flusso peso (med / max)',
    meta_duration:'Durata', meta_ratio:'Dose → Resa · Ratio', meta_ey:'Extraction Yield (EY)',
    tab_time:'⏱ Tempo', tab_pq:'Curva P·Q',
    btn_fullscreen_close:'✕ Chiudi', btn_fullscreen_tooltip:'Schermo intero',
    btn_compare_tooltip:'Seleziona come shot di confronto', btn_delete_tooltip:'Elimina shot',
    ann_title:'Note & Valutazione',    ann_coffee:'Caffè / Grani', ann_coffee_ph:'es. Ethiopia Yirgacheffe',
    ann_grinder:'Macinino', ann_grinder_ph:'es. Niche Zero',
    ann_grind_setting:'Macinatura', ann_grind_ph:'es. 23 Click',
    ann_dose:'Dose (g)', ann_dose_ph:'es. 18',
    ann_roast_date:'Data torrefazione', ann_roast_date_ph:'GG.MM.AAAA',
    ann_tds:'TDS %', ann_tds_optional:'(opzionale)',
    ann_tds_ph:'es. 9.2', ann_notes:'Note',
    ann_notes_ph:'Gusto, osservazioni, aggiustamenti …',
    ann_drink_type:'Bevanda', ann_drink_type_none:'— nessuna —',
    btn_save:'Salva', btn_saved:'✓ Salvato',
    grind_finer_urgent:'Macinare più fine', grind_finer:'Macinare leggermente più fine',
    grind_ok:'Macinatura corretta', grind_coarser:'Macinare leggermente più grosso',
    grind_coarser_urgent:'Macinare più grosso', grind_channeling:'Controllare la preparazione del puck',
    live_title:'Shot Live', live_connecting:'Connessione …', live_brewing:'Estrazione …',
    live_waiting:'In attesa dello shot …', live_disabled:'Live disabilitato (macchina spenta)',
    ref_label:'Riferimento:', ref_none:'— nessuno shot di riferimento —', ref_clear:'✕ Rimuovi',
    ref_pressure:'Rif: Pressione', ref_flow:'Rif: Flusso', ref_weight:'Rif: Peso', ref_temp:'Rif: Temp',
    live_idle_text:'Quando inizia uno shot, i dati in tempo reale appariranno qui.',
    live_time_unit:'min:sec', live_time_label:'Tempo',
    live_pressure_label:'Pressione', live_flow_label:'Flusso pompa',
    live_weight_label:'Peso', live_temp_label:'Temperatura',
    lib_beans:'Grani', lib_grinders:'Macinini',
    lib_add_bean:'+ Aggiungi grani', lib_add_grinder:'+ Aggiungi macinino',
    lib_bean_name:'Nome *', lib_bean_roaster:'Torrefazione', lib_bean_roast_date:'Data torrefazione', lib_bean_notes:'Note',
    lib_grinder_name:'Nome *', lib_grinder_notes:'Note',
    lib_bean_name_ph:'Ethiopia Yirgacheffe', lib_bean_roaster_ph:'Torrefazione Roma',
    lib_grinder_name_ph:'Niche Zero', lib_grinder_notes_ph:'Espresso: 23 Click',
    lib_cancel:'Annulla', lib_save:'Salva',
    lib_empty_beans:'Nessun grano salvato', lib_empty_grinders:'Nessun macinino salvato',
    lib_btn_edit:'Modifica', lib_btn_delete:'Elimina',
    lib_confirm_delete_bean:'Rimuovere il grano dalla libreria?',
    lib_confirm_delete_grinder:'Rimuovere il macinino dalla libreria?',
    analytics_trend:'Andamento Score', analytics_trend_30:'30 Shot', analytics_trend_90:'90 Shot', analytics_trend_all:'Tutti',
    analytics_calendar:'Calendario Shot', analytics_beans:'Statistiche Grani', analytics_profiles:'Performance Profili',
    analytics_no_trend:'Non abbastanza shot con score per il trend.',
    analytics_no_beans:'Nessun grano inserito nelle note.',
    analytics_no_profiles:'Nessun dato di profilo disponibile.',
    bean_stat_shots:'Shot', bean_stat_avg:'Score med.', bean_stat_best:'Migliore', bean_stat_duration:'Durata med.',
    confirm_trash:'Spostare lo shot nel cestino?',
    confirm_delete:(id,name,date)=>`Eliminare lo shot ${id}?\n${name} · ${date}\n\nOperazione non annullabile.`,
    confirm_perm_delete:(id)=>`Eliminare definitivamente lo shot ${id}?\nOperazione non annullabile.`,
    trash_days_left:(d)=>`eliminato tra ${d} giorno${d!==1?'i':''}`,
    trash_restore_label:'↩ Ripristina', trash_delete_title:'Elimina ora',
    freshness_title:(d)=>`Torrefatto ${d} giorni fa (ottimale: 7–21 giorni)`,
    phase_preinfusion:'Preinfusione', phase_extraction:'Estrazione',
    grind_short:(s)=>`Shot troppo corto (${s} s) — macinare più fine`,
    grind_short_slight:(s)=>`Shot leggermente corto (${s} s) — macinare leggermente più fine`,
    grind_long:(s)=>`Shot troppo lungo (${s} s) — macinare più grosso`,
    grind_long_slight:(s)=>`Shot leggermente lungo (${s} s) — macinare leggermente più grosso`,
    grind_channeling_full:'Channeling rilevato — controllare preparazione puck',
    compare_hint:'Seleziona shot per confronto',
    nav_settings:'⚙', settings_theme:'Tema', theme_dark:'Scuro', theme_light:'Chiaro', settings_language:'Lingua',
    ann_clone_btn:'↩ Clona',
    lib_bean_stock:'Scorta (g)', lib_bean_stock_ph:'es. 500',
    lib_bean_decaf:'Decaffeinato',
    lib_inv_consumed:(n)=>`${n} g usati`, lib_inv_remaining:(n)=>`${n} g rimanenti`, lib_inv_reorder:'Riordinare',
    lib_inv_total_consumed:(n)=>`${n} g totali usati`,
    lib_inv_bags:(n)=>`${n} confezione${n!==1?'i':''}`,
    lib_new_bag:'+ Nuova confezione',
    lib_new_bag_title:'Nuova confezione',
    lib_new_bag_save:'Aggiungi confezione',
    lib_bag_history:'Storico confezioni',
    lib_bag_roast_date:'Data torrefazione',
    lib_bag_stock:'Peso iniziale (g)',
    lib_recipes:'Ricette',
    lib_empty_recipes:'Nessuna ricetta',
    lib_add_recipe:'+ Aggiungi ricetta',
    lib_recipe_name:'Nome *',
    lib_recipe_drink_type:'Tipo di bevanda',
    lib_recipe_dose:'Dose (g)',
    lib_recipe_yield:'Resa (g)',
    lib_recipe_time:'Tempo (s)',
    lib_recipe_profile:'Profilo',
    lib_recipe_bean:'Grano',
    lib_recipe_notes:'Note',
    lib_recipe_brew_method:'Metodo di preparazione',
    lib_recipe_water_temp:'Temperatura acqua (°C)',
    lib_recipe_grind:'Macinatura',
    lib_recipe_steps:'Fasi del workflow',
    lib_recipe_step_ph:'Descrivi il passaggio …',
    lib_recipe_step_dur:'s',
    lib_recipe_add_step:'+ Fase',
    lib_brew_espresso:'Espresso', lib_brew_aeropress:'AeroPress', lib_brew_v60:'V60 / Pour Over',
    lib_brew_french_press:'French Press', lib_brew_moka:'Moka Pot', lib_brew_cold_brew:'Cold Brew', lib_brew_other:'Altro',
    lib_confirm_delete_recipe:'Eliminare la ricetta?',
    nav_dialin:'Calibrazione', dialin_title:'Calibrazione',
    nav_maintenance:'Manutenzione',
    maint_descaling:'Decalcificazione', maint_backflush:'Backflush', maint_grouphead:'Servizio Gruppo',
    maint_gaskets:'Guarnizioni & Filtri', maint_waterfilter:'Filtro acqua',
    maint_due:'⚠ Scaduto', maint_soon:'In scadenza', maint_never:'Mai fatto',
    maint_never_done:'Mai fatto', maint_today:'Oggi',
    maint_ago_days:(n)=>`${n} giorno${n===1?'':'i'} fa`,
    maint_shots_since:(n)=>`${n} shot dall'ultimo`,
    maint_thresh_shots:'Soglia shots', maint_thresh_days:'Soglia giorni',
    maint_ok:'✓ OK',
    maint_done_btn:'Fatto ora',
    dialin_empty:'Nessun shot per la vista di calibrazione.',
    dialin_pressure:'Pressione', dialin_duration:'Durata', dialin_dose:'Dose', dialin_ratio:'Ratio', dialin_yield:'EY %',
    degas_too_fresh:(d)=>`${d} giorni dalla torrefazione — ancora troppo fresco`,
    degas_almost:(d)=>`${d} giorni dalla torrefazione — quasi pronto`,
    degas_optimal:(d)=>`${d} giorni dalla torrefazione — finestra ottimale`,
    degas_aging:(d)=>`${d} giorni dalla torrefazione — invecchiamento`,
    degas_old:(d)=>`${d} giorni dalla torrefazione — troppo vecchio`,
    backup_title:'Backup & Restore',
    backup_desc:'Salva o ripristina tutti gli shot, le note e la libreria caffè come file JSON.',
    backup_download:'Scarica backup', backup_restore:'Ripristina backup', backup_close:'Chiudi',
    backup_confirm:'Tutti i dati attuali verranno sovrascritti. Continuare?',
    backup_invalid:'File di backup non valido.',
    backup_restored:(n)=>`Ripristinato: ${n} shot.`,
    backup_error:(msg)=>`Errore: ${msg}`,
    preheat_warming:'Riscaldamento …', preheat_ready:'Pronto per estrarre ☕',
    preheat_remain:(m,s)=>`${m}:${String(s).padStart(2,'0')} rimanenti`,
    btn_export_profile_tooltip:'Esporta profilo Gaggiuino dallo shot',
    profile_export_no_data:'Nessun dato di profilo disponibile in questo shot.',
    sidebar_hint:'Clicca sul nome per Shot A. Usa <b>⇄</b> per il confronto (Shot B).',
    sidebar_collapse:'Comprimi la barra laterale', sidebar_expand:'Espandi la barra laterale',
    error_delete:(msg)=>`Errore durante l'eliminazione: ${msg}`,
    error_generic:(msg)=>`Errore: ${msg}`,
    error_load:'Errore di caricamento',
    live_ready_status:'Pronto', live_error_status:'Errore',
    maint_by_shots:'Shots', maint_by_days:'Giorni',
    maint_grinder_section:'Macine',
    lib_scan_barcode:'⬛ Scan',
    lib_url_import:'🔗 URL',
    lib_url_placeholder:'kaffeebraun.com/…',
    lib_url_btn:'Importa',
    lib_url_importing:'Importazione …',
    lib_url_error:'Errore di importazione',
    lib_url_unsupported:'Sito non supportato',
    lib_imported_from:(src,date)=>`Importato da ${src} · ${date}`,
    scan_title:'Scansiona Barcode / QR',
    scan_attribution:'Dati prodotto da',
    scan_close:'Chiudi',
    scan_searching:'Ricerca …',
    scan_not_supported:'Scansione barcode non supportata da questo browser',
    scan_not_found:'Nessun risultato — compila i campi manualmente',
    scan_found:(name)=>`Trovato: ${name}`,
    scan_error:'Errore scansione — riprova',
    scan_glp_imported:'QR GLP importato',
    bean_qr_label:'Codice QR per questo caffè',
    nav_orders:'Ordini',
    orders_queue:'In attesa', orders_inprogress:'In preparazione', orders_history:'Cronologia',
    orders_empty:'Nessun ordine aperto',
    orders_accept:'Accetta', orders_decline:'Rifiuta', orders_complete:'✓ Fatto',
    orders_eta_label:'ETA (min)', orders_decline_ph:'Motivo …',
    orders_machine_off:'Macchina spenta — ordini non disponibili',
    orders_accept_toggle:'Accettazione ordini', orders_accept_on:'attivo', orders_accept_off:'in pausa',
    orders_stats_title:'Statistiche clienti', orders_stats_total:'Totale', orders_stats_fav:'Preferito', orders_stats_last:'Ultimo ordine', orders_stats_orders:'ordini', orders_stats_popular:'Più popolare', orders_stats_no_data:'Nessun dato',
    orders_menu_title:'Gestisci menu', orders_menu_add:'+ Aggiungi bevanda',
    orders_menu_name_ph:'Nome …', orders_menu_emoji_ph:'☕', orders_menu_save:'Aggiungi',
    orders_for:'per', orders_note_ph:'Nota …',
    orders_ago:(m)=>`${m} min fa`, orders_eta_in:(m)=>`Pronto in ${m} min`,
    orders_declined:'Rifiutato', orders_done:'Fatto', orders_new_badge:'NUOVO',
    orders_confirm_delete_item:'Rimuovere la bevanda dal menu?',
    orders_delete_entry:'Elimina voce', orders_clear_history:'Cancella cronologia',
    orders_confirm_clear_history:'Eliminare tutta la cronologia?',
    orders_notify_title:'Notifiche push',
    orders_notify_desc:'Quale dispositivo HA deve essere notificato ai cambi di stato?',
    orders_notify_no_service:'— nessun dispositivo —',
    orders_notify_save:'Salva',
    orders_notify_saved:'✓ Salvato',
    orders_notify_no_customers:'Nessun cliente ancora (devono arrivare prima degli ordini).',
    orders_notify_no_ha:'API HA non disponibile — notifiche non configurabili.',
    orders_broadcast_title:'📢 Destinatari broadcast',
    orders_broadcast_desc:'Questi dispositivi ricevono una notifica quando gli ordini vengono aperti.',
    orders_broadcast_save:'Salva',
    orders_broadcast_saved:'✓ Salvato',
    orders_trending_toggle:'Attiva/disattiva trending',
    ann_ordered_by:'Ordinato da',
  },
  fr: {
    nav_shots:'Shots', nav_live:'Live', nav_analytics:'Statistiques', nav_library:'Bibliothèque',
    sort_newest:'Récents', sort_score:'Score', sort_rating:'Note', sort_duration:'Durée',
    search_placeholder:'Profil, Café, Moulin …', trash_label:'Corbeille',
    no_sync:'pas de sync', btn_sync:'↻ Sync',
    empty_title:'Aucun shot',
    empty_desc:"Vérifiez que le contrôleur Gaggiuino est accessible à l'URL configurée et appuyez sur ↻ Sync.",
    loading:'Chargement des shots …', btn_reload:'↻ Recharger',
    meta_profile:'Profil', meta_pressure:'Pression (moy / max cible)', meta_flow:'Débit pompe (moy / cible)',
    meta_temp:'Température (moy ±σ / cible)', meta_phases:'Phases',
    meta_weight:'Poids (total / fin débit)', meta_weight_flow:'Débit poids (moy / max)',
    meta_duration:'Durée', meta_ratio:'Dose → Rendement · Ratio', meta_ey:"Taux d'extraction (EY)",
    tab_time:'⏱ Temps', tab_pq:'Courbe P·Q',
    btn_fullscreen_close:'✕ Fermer', btn_fullscreen_tooltip:'Plein écran',
    btn_compare_tooltip:'Sélectionner comme shot de comparaison', btn_delete_tooltip:'Supprimer le shot',
    ann_title:'Notes & Évaluation',    ann_coffee:'Café / Grain', ann_coffee_ph:'ex. Ethiopia Yirgacheffe',
    ann_grinder:'Moulin', ann_grinder_ph:'ex. Niche Zero',
    ann_grind_setting:'Mouture', ann_grind_ph:'ex. 23 Clics',
    ann_dose:'Dose (g)', ann_dose_ph:'ex. 18',
    ann_roast_date:'Date de torréfaction', ann_roast_date_ph:'JJ.MM.AAAA',
    ann_tds:'TDS %', ann_tds_optional:'(optionnel)',
    ann_tds_ph:'ex. 9.2', ann_notes:'Notes',
    ann_notes_ph:'Goût, observations, ajustements …',
    ann_drink_type:'Boisson', ann_drink_type_none:'— aucune —',
    btn_save:'Enregistrer', btn_saved:'✓ Enregistré',
    grind_finer_urgent:'Moudre plus fin', grind_finer:'Moudre légèrement plus fin',
    grind_ok:'La mouture est bonne', grind_coarser:'Moudre légèrement plus grossier',
    grind_coarser_urgent:'Moudre plus grossier', grind_channeling:'Vérifier la préparation du puck',
    live_title:'Shot Live', live_connecting:'Connexion …', live_brewing:'Extraction …',
    live_waiting:'En attente du shot …', live_disabled:'Live désactivé (machine éteinte)',
    ref_label:'Référence:', ref_none:'— pas de shot de référence —', ref_clear:'✕ Effacer',
    ref_pressure:'Réf: Pression', ref_flow:'Réf: Débit', ref_weight:'Réf: Poids', ref_temp:'Réf: Temp',
    live_idle_text:"Dès qu'un shot démarre, les données en temps réel apparaîtront ici.",
    live_time_unit:'min:sec', live_time_label:'Temps',
    live_pressure_label:'Pression', live_flow_label:'Débit pompe',
    live_weight_label:'Poids', live_temp_label:'Température',
    lib_beans:'Grains', lib_grinders:'Moulins',
    lib_add_bean:'+ Ajouter un grain', lib_add_grinder:'+ Ajouter un moulin',
    lib_bean_name:'Nom *', lib_bean_roaster:'Torréfacteur', lib_bean_roast_date:'Date de torréfaction', lib_bean_notes:'Notes',
    lib_grinder_name:'Nom *', lib_grinder_notes:'Notes',
    lib_bean_name_ph:'Ethiopia Yirgacheffe', lib_bean_roaster_ph:'Torréfacteur Paris',
    lib_grinder_name_ph:'Niche Zero', lib_grinder_notes_ph:'Espresso: 23 Clics',
    lib_cancel:'Annuler', lib_save:'Enregistrer',
    lib_empty_beans:'Aucun grain enregistré', lib_empty_grinders:'Aucun moulin enregistré',
    lib_btn_edit:'Modifier', lib_btn_delete:'Supprimer',
    lib_confirm_delete_bean:'Supprimer le grain de la bibliothèque ?',
    lib_confirm_delete_grinder:'Supprimer le moulin de la bibliothèque ?',
    analytics_trend:'Tendance Score', analytics_trend_30:'30 Shots', analytics_trend_90:'90 Shots', analytics_trend_all:'Tous',
    analytics_calendar:'Calendrier des Shots', analytics_beans:'Stats par Grain', analytics_profiles:'Performance des Profils',
    analytics_no_trend:'Pas assez de shots avec score pour la tendance.',
    analytics_no_beans:'Aucun grain saisi dans les notes.',
    analytics_no_profiles:'Aucune donnée de profil disponible.',
    bean_stat_shots:'Shots', bean_stat_avg:'Score moy.', bean_stat_best:'Meilleur', bean_stat_duration:'Durée moy.',
    confirm_trash:'Déplacer le shot dans la corbeille ?',
    confirm_delete:(id,name,date)=>`Supprimer le shot ${id} ?\n${name} · ${date}\n\nCette action est irréversible.`,
    confirm_perm_delete:(id)=>`Supprimer définitivement le shot ${id} ?\nCette action est irréversible.`,
    trash_days_left:(d)=>`supprimé dans ${d} jour${d!==1?'s':''}`,
    trash_restore_label:'↩ Restaurer', trash_delete_title:'Supprimer maintenant',
    freshness_title:(d)=>`Torréfié il y a ${d} jours (optimal: 7–21 jours)`,
    phase_preinfusion:'Pré-infusion', phase_extraction:'Extraction',
    grind_short:(s)=>`Shot trop court (${s} s) — moudre plus fin`,
    grind_short_slight:(s)=>`Shot légèrement court (${s} s) — moudre légèrement plus fin`,
    grind_long:(s)=>`Shot trop long (${s} s) — moudre plus grossier`,
    grind_long_slight:(s)=>`Shot légèrement long (${s} s) — moudre légèrement plus grossier`,
    grind_channeling_full:'Channeling détecté — vérifier la préparation du puck',
    compare_hint:'Sélectionner un shot pour comparaison',
    nav_settings:'⚙', settings_theme:'Thème', theme_dark:'Sombre', theme_light:'Clair', settings_language:'Langue',
    ann_clone_btn:'↩ Cloner',
    lib_bean_stock:'Stock (g)', lib_bean_stock_ph:'ex. 500',
    lib_bean_decaf:'Décaféiné',
    lib_inv_consumed:(n)=>`${n} g utilisés`, lib_inv_remaining:(n)=>`${n} g restants`, lib_inv_reorder:'Réapprovisionner',
    lib_inv_total_consumed:(n)=>`${n} g utilisés au total`,
    lib_inv_bags:(n)=>`${n} sachet${n!==1?'s':''}`,
    lib_new_bag:'+ Nouveau sachet',
    lib_new_bag_title:'Nouveau sachet',
    lib_new_bag_save:'Ajouter sachet',
    lib_bag_history:'Historique sachets',
    lib_bag_roast_date:'Date de torréfaction',
    lib_bag_stock:'Poids initial (g)',
    lib_recipes:'Recettes',
    lib_empty_recipes:'Aucune recette',
    lib_add_recipe:'+ Ajouter une recette',
    lib_recipe_name:'Nom *',
    lib_recipe_drink_type:'Type de boisson',
    lib_recipe_dose:'Dose (g)',
    lib_recipe_yield:'Rendement (g)',
    lib_recipe_time:'Temps (s)',
    lib_recipe_profile:'Profil',
    lib_recipe_bean:'Grain',
    lib_recipe_notes:'Notes',
    lib_recipe_brew_method:'Méthode de préparation',
    lib_recipe_water_temp:'Température de l\'eau (°C)',
    lib_recipe_grind:'Mouture',
    lib_recipe_steps:'Étapes du workflow',
    lib_recipe_step_ph:'Décrire l\'étape …',
    lib_recipe_step_dur:'s',
    lib_recipe_add_step:'+ Étape',
    lib_brew_espresso:'Espresso', lib_brew_aeropress:'AeroPress', lib_brew_v60:'V60 / Pour Over',
    lib_brew_french_press:'French Press', lib_brew_moka:'Moka Pot', lib_brew_cold_brew:'Cold Brew', lib_brew_other:'Autre',
    lib_confirm_delete_recipe:'Supprimer la recette ?',
    nav_dialin:'Réglage', dialin_title:'Réglage',
    nav_maintenance:'Entretien',
    maint_descaling:'Détartrage', maint_backflush:'Backflush', maint_grouphead:'Service groupe',
    maint_gaskets:'Joints & Filtres', maint_waterfilter:'Filtre eau',
    maint_due:'⚠ À faire', maint_soon:'Bientôt dû', maint_never:'Jamais fait',
    maint_never_done:'Jamais fait', maint_today:"Aujourd'hui",
    maint_ago_days:(n)=>`Il y a ${n} jour${n===1?'':'s'}`,
    maint_shots_since:(n)=>`${n} shot${n===1?'':'s'} depuis`,
    maint_thresh_shots:'Seuil shots', maint_thresh_days:'Seuil jours',
    maint_ok:'✓ OK',
    maint_done_btn:'Fait maintenant',
    dialin_empty:'Aucun shot pour la vue de réglage.',
    dialin_pressure:'Pression', dialin_duration:'Durée', dialin_dose:'Dose', dialin_ratio:'Ratio', dialin_yield:'EY %',
    degas_too_fresh:(d)=>`${d} jours depuis la torréfaction — encore trop frais`,
    degas_almost:(d)=>`${d} jours depuis la torréfaction — presque prêt`,
    degas_optimal:(d)=>`${d} jours depuis la torréfaction — fenêtre optimale`,
    degas_aging:(d)=>`${d} jours depuis la torréfaction — vieillissement`,
    degas_old:(d)=>`${d} jours depuis la torréfaction — trop vieux`,
    backup_title:'Backup & Restore',
    backup_desc:'Sauvegardez ou restaurez tous les shots, notes et la bibliothèque café en JSON.',
    backup_download:'Télécharger la sauvegarde', backup_restore:'Restaurer la sauvegarde', backup_close:'Fermer',
    backup_confirm:'Toutes les données actuelles seront écrasées. Continuer ?',
    backup_invalid:'Fichier de sauvegarde invalide.',
    backup_restored:(n)=>`Restauré : ${n} shot${n!==1?'s':''}.`,
    backup_error:(msg)=>`Erreur : ${msg}`,
    preheat_warming:'Chauffe en cours …', preheat_ready:'Prêt à extraire ☕',
    preheat_remain:(m,s)=>`${m}:${String(s).padStart(2,'0')} restantes`,
    btn_export_profile_tooltip:'Exporter le profil Gaggiuino depuis le shot',
    profile_export_no_data:'Aucune donnée de profil disponible dans ce shot.',
    sidebar_hint:'Cliquez sur le nom pour Shot A. Utilisez <b>⇄</b> pour la comparaison (Shot B).',
    sidebar_collapse:'Réduire la barre latérale', sidebar_expand:'Développer la barre latérale',
    error_delete:(msg)=>`Erreur lors de la suppression : ${msg}`,
    error_generic:(msg)=>`Erreur : ${msg}`,
    error_load:'Erreur de chargement',
    live_ready_status:'Prêt', live_error_status:'Erreur',
    maint_by_shots:'Shots', maint_by_days:'Jours',
    maint_grinder_section:'Moulins',
    lib_scan_barcode:'⬛ Scan',
    lib_url_import:'🔗 URL',
    lib_url_placeholder:'kaffeebraun.com/…',
    lib_url_btn:'Importer',
    lib_url_importing:'Import en cours …',
    lib_url_error:"Erreur d'importation",
    lib_url_unsupported:'Site non supporté',
    lib_imported_from:(src,date)=>`Importé de ${src} · ${date}`,
    scan_title:'Scanner Codes-barres / QR',
    scan_attribution:'Données produit de',
    scan_close:'Fermer',
    scan_searching:'Recherche …',
    scan_not_supported:"Le scan de codes-barres n'est pas supporté par ce navigateur",
    scan_not_found:'Aucun résultat — remplir les champs manuellement',
    scan_found:(name)=>`Trouvé : ${name}`,
    scan_error:'Erreur de scan — réessayer',
    scan_glp_imported:'QR GLP importé',
    bean_qr_label:'Code QR pour ce café',
    nav_orders:'Commandes',
    orders_queue:"File d'attente", orders_inprogress:'En cours', orders_history:'Historique',
    orders_empty:'Aucune commande ouverte',
    orders_accept:'Accepter', orders_decline:'Refuser', orders_complete:'✓ Terminé',
    orders_eta_label:'ETA (min)', orders_decline_ph:'Raison …',
    orders_machine_off:'Machine éteinte — commandes non disponibles',
    orders_accept_toggle:'Acceptation des commandes', orders_accept_on:'actif', orders_accept_off:'en pause',
    orders_stats_title:'Statistiques clients', orders_stats_total:'Total', orders_stats_fav:'Favori', orders_stats_last:'Dernière commande', orders_stats_orders:'commandes', orders_stats_popular:'Le plus populaire', orders_stats_no_data:'Pas encore de données',
    orders_menu_title:'Gérer le menu', orders_menu_add:'+ Ajouter une boisson',
    orders_menu_name_ph:'Nom …', orders_menu_emoji_ph:'☕', orders_menu_save:'Ajouter',
    orders_for:'pour', orders_note_ph:'Note …',
    orders_ago:(m)=>`Il y a ${m} min`, orders_eta_in:(m)=>`Prêt dans ${m} min`,
    orders_declined:'Refusé', orders_done:'Terminé', orders_new_badge:'NOUVEAU',
    orders_confirm_delete_item:'Supprimer la boisson du menu ?',
    orders_delete_entry:'Supprimer', orders_clear_history:'Effacer l\'historique',
    orders_confirm_clear_history:'Supprimer tout l\'historique ?',
    orders_notify_title:'Notifications push',
    orders_notify_desc:'Quel appareil HA doit être notifié lors des changements de statut ?',
    orders_notify_no_service:'— pas d\'appareil —',
    orders_notify_save:'Enregistrer',
    orders_notify_saved:'✓ Enregistré',
    orders_notify_no_customers:'Aucun client encore (des commandes doivent d\'abord arriver).',
    orders_notify_no_ha:'API HA indisponible — notifications non configurables.',
    orders_broadcast_title:'📢 Destinataires diffusion',
    orders_broadcast_desc:'Ces appareils reçoivent une notification quand les commandes sont ouvertes.',
    orders_broadcast_save:'Enregistrer',
    orders_broadcast_saved:'✓ Enregistré',
    orders_trending_toggle:'Activer/désactiver tendance',
    ann_ordered_by:'Commandé par',
  },
  es: {
    nav_shots:'Shots', nav_live:'Live', nav_analytics:'Estadísticas', nav_library:'Biblioteca',
    sort_newest:'Recientes', sort_score:'Score', sort_rating:'Valoración', sort_duration:'Duración',
    search_placeholder:'Perfil, Café, Molino …', trash_label:'Papelera',
    no_sync:'sin sync', btn_sync:'↻ Sync',
    empty_title:'Sin shots',
    empty_desc:'Asegúrate de que el controlador Gaggiuino sea accesible en la URL configurada y pulsa ↻ Sync.',
    loading:'Cargando shots …', btn_reload:'↻ Recargar',
    meta_profile:'Perfil', meta_pressure:'Presión (med / máx objetivo)', meta_flow:'Flujo bomba (med / objetivo)',
    meta_temp:'Temperatura (med ±σ / objetivo)', meta_phases:'Fases',
    meta_weight:'Peso (total / fin flujo)', meta_weight_flow:'Flujo peso (med / máx)',
    meta_duration:'Duración', meta_ratio:'Dosis → Rendimiento · Ratio', meta_ey:'Rendimiento extracción (EY)',
    tab_time:'⏱ Tiempo', tab_pq:'Curva P·Q',
    btn_fullscreen_close:'✕ Cerrar', btn_fullscreen_tooltip:'Pantalla completa',
    btn_compare_tooltip:'Seleccionar como shot de comparación', btn_delete_tooltip:'Eliminar shot',
    ann_title:'Notas & Valoración',    ann_coffee:'Café / Grano', ann_coffee_ph:'ej. Ethiopia Yirgacheffe',
    ann_grinder:'Molino', ann_grinder_ph:'ej. Niche Zero',
    ann_grind_setting:'Molturación', ann_grind_ph:'ej. 23 Clicks',
    ann_dose:'Dosis (g)', ann_dose_ph:'ej. 18',
    ann_roast_date:'Fecha de tueste', ann_roast_date_ph:'DD.MM.AAAA',
    ann_tds:'TDS %', ann_tds_optional:'(opcional)',
    ann_tds_ph:'ej. 9.2', ann_notes:'Notas',
    ann_notes_ph:'Sabor, observaciones, ajustes …',
    ann_drink_type:'Bebida', ann_drink_type_none:'— ninguna —',
    btn_save:'Guardar', btn_saved:'✓ Guardado',
    grind_finer_urgent:'Moler más fino', grind_finer:'Moler ligeramente más fino',
    grind_ok:'La molturación es correcta', grind_coarser:'Moler ligeramente más grueso',
    grind_coarser_urgent:'Moler más grueso', grind_channeling:'Revisar preparación del puck',
    live_title:'Shot Live', live_connecting:'Conectando …', live_brewing:'Extrayendo …',
    live_waiting:'Esperando shot …', live_disabled:'Live desactivado (máquina apagada)',
    ref_label:'Referencia:', ref_none:'— sin shot de referencia —', ref_clear:'✕ Quitar',
    ref_pressure:'Ref: Presión', ref_flow:'Ref: Flujo', ref_weight:'Ref: Peso', ref_temp:'Ref: Temp',
    live_idle_text:'Cuando comience un shot, los datos en tiempo real aparecerán aquí.',
    live_time_unit:'min:seg', live_time_label:'Tiempo',
    live_pressure_label:'Presión', live_flow_label:'Flujo bomba',
    live_weight_label:'Peso', live_temp_label:'Temperatura',
    lib_beans:'Granos', lib_grinders:'Molinos',
    lib_add_bean:'+ Añadir grano', lib_add_grinder:'+ Añadir molino',
    lib_bean_name:'Nombre *', lib_bean_roaster:'Tostadero', lib_bean_roast_date:'Fecha de tueste', lib_bean_notes:'Notas',
    lib_grinder_name:'Nombre *', lib_grinder_notes:'Notas',
    lib_bean_name_ph:'Ethiopia Yirgacheffe', lib_bean_roaster_ph:'Tostadero Madrid',
    lib_grinder_name_ph:'Niche Zero', lib_grinder_notes_ph:'Espresso: 23 Clicks',
    lib_cancel:'Cancelar', lib_save:'Guardar',
    lib_empty_beans:'No hay granos guardados', lib_empty_grinders:'No hay molinos guardados',
    lib_btn_edit:'Editar', lib_btn_delete:'Eliminar',
    lib_confirm_delete_bean:'¿Eliminar el grano de la biblioteca?',
    lib_confirm_delete_grinder:'¿Eliminar el molino de la biblioteca?',
    analytics_trend:'Tendencia Score', analytics_trend_30:'30 Shots', analytics_trend_90:'90 Shots', analytics_trend_all:'Todos',
    analytics_calendar:'Calendario de Shots', analytics_beans:'Estadísticas por Grano', analytics_profiles:'Rendimiento de Perfiles',
    analytics_no_trend:'No hay suficientes shots con score.',
    analytics_no_beans:'No se han introducido granos en las notas.',
    analytics_no_profiles:'No hay datos de perfil disponibles.',
    bean_stat_shots:'Shots', bean_stat_avg:'Score med.', bean_stat_best:'Mejor', bean_stat_duration:'Duración med.',
    confirm_trash:'¿Mover el shot a la papelera?',
    confirm_delete:(id,name,date)=>`¿Eliminar shot ${id}?\n${name} · ${date}\n\nEsta acción no se puede deshacer.`,
    confirm_perm_delete:(id)=>`¿Eliminar definitivamente el shot ${id}?\nEsta acción no se puede deshacer.`,
    trash_days_left:(d)=>`eliminado en ${d} día${d!==1?'s':''}`,
    trash_restore_label:'↩ Restaurar', trash_delete_title:'Eliminar ahora',
    freshness_title:(d)=>`Tostado hace ${d} días (óptimo: 7–21 días)`,
    phase_preinfusion:'Preinfusión', phase_extraction:'Extracción',
    grind_short:(s)=>`Shot demasiado corto (${s} s) — moler más fino`,
    grind_short_slight:(s)=>`Shot ligeramente corto (${s} s) — moler ligeramente más fino`,
    grind_long:(s)=>`Shot demasiado largo (${s} s) — moler más grueso`,
    grind_long_slight:(s)=>`Shot ligeramente largo (${s} s) — moler ligeramente más grueso`,
    grind_channeling_full:'Channeling detectado — revisar preparación del puck',
    compare_hint:'Seleccionar shot para comparación',
    nav_settings:'⚙', settings_theme:'Tema', theme_dark:'Oscuro', theme_light:'Claro', settings_language:'Idioma',
    ann_clone_btn:'↩ Clonar',
    lib_bean_stock:'Stock (g)', lib_bean_stock_ph:'ej. 500',
    lib_bean_decaf:'Descafeinado',
    lib_inv_consumed:(n)=>`${n} g usados`, lib_inv_remaining:(n)=>`${n} g restantes`, lib_inv_reorder:'Repedir',
    lib_inv_total_consumed:(n)=>`${n} g usados en total`,
    lib_inv_bags:(n)=>`${n} bolsa${n!==1?'s':''}`,
    lib_new_bag:'+ Nueva bolsa',
    lib_new_bag_title:'Nueva bolsa',
    lib_new_bag_save:'Añadir bolsa',
    lib_bag_history:'Historial de bolsas',
    lib_bag_roast_date:'Fecha de tostado',
    lib_bag_stock:'Peso inicial (g)',
    lib_recipes:'Recetas',
    lib_empty_recipes:'Sin recetas',
    lib_add_recipe:'+ Añadir receta',
    lib_recipe_name:'Nombre *',
    lib_recipe_drink_type:'Tipo de bebida',
    lib_recipe_dose:'Dosis (g)',
    lib_recipe_yield:'Rendimiento (g)',
    lib_recipe_time:'Tiempo (s)',
    lib_recipe_profile:'Perfil',
    lib_recipe_bean:'Grano',
    lib_recipe_notes:'Notas',
    lib_recipe_brew_method:'Método de preparación',
    lib_recipe_water_temp:'Temperatura del agua (°C)',
    lib_recipe_grind:'Molienda',
    lib_recipe_steps:'Pasos del workflow',
    lib_recipe_step_ph:'Describir el paso …',
    lib_recipe_step_dur:'s',
    lib_recipe_add_step:'+ Paso',
    lib_brew_espresso:'Espresso', lib_brew_aeropress:'AeroPress', lib_brew_v60:'V60 / Pour Over',
    lib_brew_french_press:'French Press', lib_brew_moka:'Moka Pot', lib_brew_cold_brew:'Cold Brew', lib_brew_other:'Otro',
    lib_confirm_delete_recipe:'¿Eliminar la receta?',
    nav_dialin:'Calibración', dialin_title:'Calibración',
    nav_maintenance:'Mantenimiento',
    maint_descaling:'Descalcificación', maint_backflush:'Backflush', maint_grouphead:'Servicio grupo',
    maint_gaskets:'Juntas & Filtros', maint_waterfilter:'Filtro agua',
    maint_due:'⚠ Vencido', maint_soon:'Por vencer', maint_never:'Nunca hecho',
    maint_never_done:'Nunca hecho', maint_today:'Hoy',
    maint_ago_days:(n)=>`Hace ${n} día${n===1?'':'s'}`,
    maint_shots_since:(n)=>`${n} shot${n===1?'':'s'} desde último`,
    maint_thresh_shots:'Límite shots', maint_thresh_days:'Límite días',
    maint_ok:'✓ OK',
    maint_done_btn:'Hecho ahora',
    dialin_empty:'No hay shots para la vista de calibración.',
    dialin_pressure:'Presión', dialin_duration:'Duración', dialin_dose:'Dosis', dialin_ratio:'Ratio', dialin_yield:'EY %',
    degas_too_fresh:(d)=>`${d} días desde el tueste — aún demasiado fresco`,
    degas_almost:(d)=>`${d} días desde el tueste — casi listo`,
    degas_optimal:(d)=>`${d} días desde el tueste — ventana óptima`,
    degas_aging:(d)=>`${d} días desde el tueste — envejeciendo`,
    degas_old:(d)=>`${d} días desde el tueste — demasiado viejo`,
    backup_title:'Backup & Restore',
    backup_desc:'Guarda o restaura todos los shots, notas y la biblioteca de café como archivo JSON.',
    backup_download:'Descargar copia de seguridad', backup_restore:'Restaurar copia de seguridad', backup_close:'Cerrar',
    backup_confirm:'Todos los datos actuales serán reemplazados. ¿Continuar?',
    backup_invalid:'Archivo de copia de seguridad no válido.',
    backup_restored:(n)=>`Restaurado: ${n} shot${n!==1?'s':''}.`,
    backup_error:(msg)=>`Error: ${msg}`,
    preheat_warming:'Calentando …', preheat_ready:'Listo para extraer ☕',
    preheat_remain:(m,s)=>`${m}:${String(s).padStart(2,'0')} restante`,
    btn_export_profile_tooltip:'Exportar perfil Gaggiuino desde el shot',
    profile_export_no_data:'No hay datos de perfil disponibles en este shot.',
    sidebar_hint:'Haz clic en el nombre para Shot A. Usa <b>⇄</b> para la comparación (Shot B).',
    sidebar_collapse:'Contraer barra lateral', sidebar_expand:'Expandir barra lateral',
    error_delete:(msg)=>`Error al eliminar: ${msg}`,
    error_generic:(msg)=>`Error: ${msg}`,
    error_load:'Error al cargar',
    live_ready_status:'Listo', live_error_status:'Error',
    maint_by_shots:'Shots', maint_by_days:'Días',
    maint_grinder_section:'Molinos',
    lib_scan_barcode:'⬛ Scan',
    lib_url_import:'🔗 URL',
    lib_url_placeholder:'kaffeebraun.com/…',
    lib_url_btn:'Importar',
    lib_url_importing:'Importando …',
    lib_url_error:'Error de importación',
    lib_url_unsupported:'Sitio no compatible',
    lib_imported_from:(src,date)=>`Importado de ${src} · ${date}`,
    scan_title:'Escanear Código / QR',
    scan_attribution:'Datos del producto de',
    scan_close:'Cerrar',
    scan_searching:'Buscando …',
    scan_not_supported:'El escáner de códigos de barras no es compatible con este navegador',
    scan_not_found:'Sin resultados — rellenar campos manualmente',
    scan_found:(name)=>`Encontrado: ${name}`,
    scan_error:'Error de escaneo — vuelve a intentarlo',
    scan_glp_imported:'QR GLP importado',
    bean_qr_label:'Código QR para este café',
    nav_orders:'Pedidos',
    orders_queue:'Cola', orders_inprogress:'En preparación', orders_history:'Historial',
    orders_empty:'No hay pedidos abiertos',
    orders_accept:'Aceptar', orders_decline:'Rechazar', orders_complete:'✓ Listo',
    orders_eta_label:'ETA (min)', orders_decline_ph:'Motivo …',
    orders_machine_off:'Máquina apagada — pedidos no disponibles',
    orders_accept_toggle:'Aceptación de pedidos', orders_accept_on:'activo', orders_accept_off:'pausado',
    orders_stats_title:'Estadísticas de clientes', orders_stats_total:'Total', orders_stats_fav:'Favorito', orders_stats_last:'Último pedido', orders_stats_orders:'pedidos', orders_stats_popular:'Más popular', orders_stats_no_data:'Sin datos aún',
    orders_menu_title:'Gestionar menú', orders_menu_add:'+ Agregar bebida',
    orders_menu_name_ph:'Nombre …', orders_menu_emoji_ph:'☕', orders_menu_save:'Agregar',
    orders_for:'para', orders_note_ph:'Nota …',
    orders_ago:(m)=>`Hace ${m} min`, orders_eta_in:(m)=>`Listo en ${m} min`,
    orders_declined:'Rechazado', orders_done:'Listo', orders_new_badge:'NUEVO',
    orders_confirm_delete_item:'¿Eliminar bebida del menú?',
    orders_delete_entry:'Eliminar entrada', orders_clear_history:'Borrar historial',
    orders_confirm_clear_history:'¿Borrar todo el historial?',
    orders_notify_title:'Notificaciones push',
    orders_notify_desc:'¿Qué dispositivo de HA debe notificarse en los cambios de estado?',
    orders_notify_no_service:'— sin dispositivo —',
    orders_notify_save:'Guardar',
    orders_notify_saved:'✓ Guardado',
    orders_notify_no_customers:'Aún no hay clientes (primero deben llegar pedidos).',
    orders_notify_no_ha:'API de HA no disponible — las notificaciones no se pueden configurar.',
    orders_broadcast_title:'📢 Destinatarios difusión',
    orders_broadcast_desc:'Estos dispositivos reciben una notificación cuando se abren los pedidos.',
    orders_broadcast_save:'Guardar',
    orders_broadcast_saved:'✓ Guardado',
    orders_trending_toggle:'Activar/desactivar tendencia',
    ann_ordered_by:'Pedido por',
  },
};

export const MAINT_META = {
  descaling:   { icon: '🧪', key: 'maint_descaling'   },
  backflush:   { icon: '🔄', key: 'maint_backflush'   },
  grouphead:   { icon: '🔧', key: 'maint_grouphead'   },
  gaskets:     { icon: '⭕', key: 'maint_gaskets'     },
  waterfilter: { icon: '💧', key: 'maint_waterfilter' },
};

// ── Phase background plugin ───────────────────────────────────────────────
export const phasePlugin = {
  id: 'phases',
  beforeDatasetsDraw(chart, _args, opts) {
    if (!opts?.preinfusion) return;
    const { ctx, chartArea: { top, bottom, left, right }, scales: { x } } = chart;
    const preEnd   = Math.min(Math.max(x.getPixelForValue(opts.preinfusion), left), right);
    const totalEnd = Math.min(Math.max(x.getPixelForValue(opts.preinfusion + opts.extraction), left), right);

    ctx.save();

    if (preEnd > left) {
      ctx.fillStyle = 'rgba(52,152,219,0.13)';
      ctx.fillRect(left, top, preEnd - left, bottom - top);
    }
    if (totalEnd > preEnd) {
      ctx.fillStyle = 'rgba(243,156,18,0.10)';
      ctx.fillRect(preEnd, top, totalEnd - preEnd, bottom - top);
    }

    // Phase boundary line
    ctx.beginPath();
    ctx.strokeStyle = 'rgba(255,255,255,0.35)';
    ctx.setLineDash([5, 4]);
    ctx.lineWidth = 1.5;
    ctx.moveTo(preEnd, top);
    ctx.lineTo(preEnd, bottom);
    ctx.stroke();

    // Labels with pill background — needs t() from i18n
    // We call window.t() to avoid circular dependency with i18n.js
    ctx.setLineDash([]);
    ctx.font = '600 11px Figtree, sans-serif';
    const labelY = top + 34;
    if (preEnd - left > 40) {
      const lbl = window.t ? window.t('phase_preinfusion') : 'Preinfusion';
      const w   = ctx.measureText(lbl).width;
      ctx.fillStyle = 'rgba(52,152,219,0.22)';
      ctx.beginPath(); ctx.roundRect(left + 6, labelY - 12, w + 12, 16, 4); ctx.fill();
      ctx.fillStyle = 'rgba(147,197,253,0.9)';
      ctx.textAlign = 'left'; ctx.fillText(lbl, left + 12, labelY);
    }
    if (totalEnd - preEnd > 60) {
      const lbl = window.t ? window.t('phase_extraction') : 'Extraktion';
      const w   = ctx.measureText(lbl).width;
      ctx.fillStyle = 'rgba(243,156,18,0.22)';
      ctx.beginPath(); ctx.roundRect(preEnd + 6, labelY - 12, w + 12, 16, 4); ctx.fill();
      ctx.fillStyle = 'rgba(251,191,36,0.9)';
      ctx.textAlign = 'left'; ctx.fillText(lbl, preEnd + 12, labelY);
    }

    ctx.restore();
  }
};

// ── Mobile: clear tooltip + crosshair on touchend ─────────────────────────
/**
 * Attach a touchend listener to a Chart.js instance so the tooltip and
 * corsair crosshair disappear when the user lifts their finger on mobile.
 */
export function clearChartOnTouchEnd(chart) {
  chart.canvas.addEventListener('touchend', () => {
    if (chart.corsair) chart.corsair = { draw: false };
    chart.tooltip.setActiveElements([], { x: 0, y: 0 });
    chart.update('none');
  }, { passive: true });
}

// ── Corsair crosshair ─────────────────────────────────────────────────────
export const corsairPlugin = {
  id: 'corsair',
  defaults: { width: 1, color: 'rgba(255,255,255,0.35)', dash: [4,4] },
  afterInit:  c => { c.corsair = { x: 0, y: 0 }; },
  afterEvent: (c, args) => { c.corsair = { x: args.event.x, y: args.event.y, draw: args.inChartArea }; c.draw(); },
  beforeDatasetsDraw: (c, _a, opts) => {
    if (!c.corsair) return;
    const { ctx } = c;
    const { top, bottom } = c.chartArea;
    const { x, draw } = c.corsair;
    if (!draw) return;
    ctx.save();
    ctx.beginPath();
    ctx.lineWidth = opts.width; ctx.strokeStyle = opts.color; ctx.setLineDash(opts.dash);
    ctx.moveTo(x, bottom); ctx.lineTo(x, top); ctx.stroke();
    ctx.restore();
  }
};
