name: "Gaggiuino Local Profiler (GLP)"
description: "Lokaler Profiler für Gaggiuino Shot-Analysen"
version: "1.2.4"
slug: "gaggiuino_local_profiler"
init: false
arch:
  - aarch64
  - amd64
  - armv7
panel_icon: "mdi:coffee-maker-check"
panel_title: "GLP"
ingress: true
ingress_port: 8099  # <--- Hier auf 8099 ändern, passend zur server.js!
# Neue Konfigurationsfelder für Home Assistant
options:
  machine_address: "gaggia.local"
schema:
  machine_address: str