package db

import (
	"database/sql"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"testing"
)

// columnInfo mirrors one row of `PRAGMA table_info(...)` — the same shape
// testdata/gen_node_schema.js dumps from a real better-sqlite3 database
// driven by the actual lib/db.js code (not a hand-transcribed guess at it).
type columnInfo struct {
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	NotNull   int         `json:"notnull"`
	DfltValue interface{} `json:"dflt_value"`
	PK        int         `json:"pk"`
}

type indexInfo struct {
	Name  string `json:"name"`
	Table string `json:"table"`
}

type schemaFixture struct {
	Tables  map[string][]columnInfo `json:"tables"`
	Indexes []indexInfo             `json:"indexes"`
}

// TestSchemaMatchesNodeFixture is the "critical verification step" the
// Phase 1a plan calls for: it compares this package's schema against
// testdata/node_schema.json, a fixture generated by
// testdata/gen_node_schema.js running lib/db.js's real initSchema() +
// migrateMachineColumns() + migrateMachineTheme() + ensureInstallId()
// against a real better-sqlite3 database (see that script's header comment
// for exactly what it captures and why a fresh install never exercises
// fixSchema() or the flat-JSON migrate()).
//
// What is compared, and why it's sufficient: for every table, the full
// `PRAGMA table_info` row per column (name, declared type, NOT NULL, default
// value, primary-key position) — this pins column set, order, types,
// nullability and defaults simultaneously, which is everything a byte-level
// CREATE TABLE diff would also catch, without being sensitive to
// non-semantic differences (whitespace, comment text, IF NOT EXISTS
// phrasing) between the Go and Node source text. Named indexes (from
// sqlite_master, excluding the unnamed indexes SQLite creates implicitly for
// PRIMARY KEY/UNIQUE constraints — table_info's pk column already covers
// those) are compared by (name, table) pair. The set of tables itself is
// compared too, so a missing or extra table fails the test.
//
// Regenerate the fixture after any lib/db.js schema change:
//
//	node go/internal/db/testdata/gen_node_schema.js
func TestSchemaMatchesNodeFixture(t *testing.T) {
	fixtureBytes, err := os.ReadFile(filepath.Join("testdata", "node_schema.json"))
	if err != nil {
		t.Fatalf("reading node_schema.json fixture: %v", err)
	}
	var want schemaFixture
	if err := json.Unmarshal(fixtureBytes, &want); err != nil {
		t.Fatalf("parsing node_schema.json fixture: %v", err)
	}

	dbPath := filepath.Join(t.TempDir(), "glp.db")
	sqlDB, err := Open(dbPath)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer sqlDB.Close()

	got := dumpSchema(t, sqlDB)

	// goOnlyTables / goOnlyIndexes: additive objects the Go server creates
	// that Node's lib/db.js has no equivalent for (see the CREATE ... IF NOT
	// EXISTS Execs in db.go, kept out of the Node-pinned schemaSQL constant
	// on purpose). They are dropped from the Go dump before the Node-parity
	// comparison; extend these when adding another Go-only table/index.
	goOnlyTables := map[string]bool{
		"shot_score_cache": true, // #957 read-through score cache
	}
	goOnlyIndexes := map[string]bool{
		"idx_shots_ts_id": true, // #957 keyset-page order
	}
	for name := range goOnlyTables {
		if _, ok := got.Tables[name]; !ok {
			t.Errorf("expected Go-only table %q to exist", name)
		}
		delete(got.Tables, name)
	}
	filteredIdx := got.Indexes[:0]
	for _, idx := range got.Indexes {
		if goOnlyIndexes[idx.Name] {
			continue
		}
		filteredIdx = append(filteredIdx, idx)
	}
	got.Indexes = filteredIdx

	wantTables := sortedKeys(want.Tables)
	gotTables := sortedKeys(got.Tables)
	if !reflect.DeepEqual(wantTables, gotTables) {
		t.Fatalf("table set mismatch:\n  node: %v\n  go:   %v", wantTables, gotTables)
	}
	for _, table := range wantTables {
		if !reflect.DeepEqual(want.Tables[table], got.Tables[table]) {
			t.Errorf("table %q column mismatch:\n  node: %+v\n  go:   %+v", table, want.Tables[table], got.Tables[table])
		}
	}

	sortIndexes(want.Indexes)
	sortIndexes(got.Indexes)
	if !reflect.DeepEqual(want.Indexes, got.Indexes) {
		t.Errorf("index set mismatch:\n  node: %+v\n  go:   %+v", want.Indexes, got.Indexes)
	}
}

func dumpSchema(t *testing.T, sqlDB *sql.DB) schemaFixture {
	t.Helper()

	rows, err := sqlDB.Query(`SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name`)
	if err != nil {
		t.Fatalf("listing tables: %v", err)
	}
	var tableNames []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			t.Fatalf("scanning table name: %v", err)
		}
		tableNames = append(tableNames, name)
	}
	rows.Close()

	result := schemaFixture{Tables: map[string][]columnInfo{}}
	for _, table := range tableNames {
		colRows, err := sqlDB.Query(`SELECT name, type, "notnull", dflt_value, pk FROM pragma_table_info(?)`, table)
		if err != nil {
			t.Fatalf("PRAGMA table_info(%s): %v", table, err)
		}
		var cols []columnInfo
		for colRows.Next() {
			var c columnInfo
			if err := colRows.Scan(&c.Name, &c.Type, &c.NotNull, &c.DfltValue, &c.PK); err != nil {
				colRows.Close()
				t.Fatalf("scanning table_info row for %s: %v", table, err)
			}
			cols = append(cols, c)
		}
		colRows.Close()
		result.Tables[table] = cols
	}

	idxRows, err := sqlDB.Query(`SELECT name, tbl_name FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name`)
	if err != nil {
		t.Fatalf("listing indexes: %v", err)
	}
	defer idxRows.Close()
	for idxRows.Next() {
		var idx indexInfo
		if err := idxRows.Scan(&idx.Name, &idx.Table); err != nil {
			t.Fatalf("scanning index row: %v", err)
		}
		result.Indexes = append(result.Indexes, idx)
	}

	return result
}

func sortedKeys(m map[string][]columnInfo) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortIndexes(idx []indexInfo) {
	sort.Slice(idx, func(i, j int) bool { return idx[i].Name < idx[j].Name })
}
