// Package proto is the Go port of lib/gaggiuino-proto.js: the wire schema
// for the Gaggiuino machine's binary WebSocket protocol (real Protocol
// Buffers, confirmed against the upstream docs — see go/RESEARCH.md's "The
// wire format is real binary Protocol Buffers" section). It defines every
// message type lib/gaggiuino-proto.js defines, plus a hand-written
// binary encoder/decoder for each — not generated code.
//
// # Why hand-written instead of protoc-gen-go
//
// go/RESEARCH.md documents the blocker this package starts from: no
// `.proto` source files exist in this repo, in node_modules, or in any
// branch/tag of the firmware repo this spike could locate — the firmware
// is closed-source and lib/gaggiuino-proto.js's own header comment says
// its message definitions were "reconstructed field-for-field from the
// machine's own web UI bundle... and verified live against a real
// machine" (profile CRUD), with a documented subset transcribed from
// Gaggiuino's own published API docs (#597, sensor/system-state/command
// messages). RESEARCH.md's recommended fallback — cross-check the two
// independent sources (the published websocket.md doc's inline schema
// blocks and lib/gaggiuino-proto.js's own field descriptors) field-by-
// field — is what schema.proto below records the result of.
//
// This environment additionally has no `protoc`/`protoc-gen-go` binary
// installed (confirmed: `which protoc protoc-gen-go` finds neither), so
// even with real `.proto` sources in hand, codegen isn't available here.
// schema.proto is written in real, syntactically valid proto3 — a future
// environment with protoc-gen-go available can regenerate wire-compatible
// bindings from it directly — but the structs and Marshal/Unmarshal
// methods in messages.go are hand-written against the same field
// numbers/wire types schema.proto documents, verified by:
//
//  1. wire_test.go's low-level encoder/decoder tests (varint, fixed32,
//     length-delimited framing) against manually computed byte sequences.
//  2. messages_test.go's round-trip tests (Marshal then Unmarshal returns
//     the original value) for every message type.
//  3. node_vectors_test.go's cross-validation against lib/gaggiuino-proto.js
//     itself: testdata/node_vectors.json is generated by
//     testdata/gen_node_vectors.js, which drives the real
//     @protobuf-ts/runtime-backed encoder/decoder this app already ships
//     and depends on in production (not a reimplementation) to produce
//     {hex, decoded} pairs for representative instances of every message
//     type — deliberately including zero-valued fields, populated nested
//     messages, and (for ProfileDto) a populated repeated field, since
//     proto3's default-value wire omission makes the zero-value case the
//     one most likely to hide an encoding bug. node_vectors_test.go decodes
//     each hex blob with this package's own Unmarshal and asserts the
//     result matches the recorded `decoded` JSON field-for-field, then
//     re-encodes with this package's own Marshal and asserts the output
//     hex is byte-identical to Node's. This is real ground-truth
//     verification against the actual code that talks to real machines in
//     production today — not a synthetic vector checked only against
//     itself. Regenerate the fixture with
//     `node internal/machines/proto/testdata/gen_node_vectors.js` (run
//     from the repo's Node root, which has @protobuf-ts/runtime installed)
//     after any lib/gaggiuino-proto.js schema change.
//
// No live-hardware verification happens in this package — go/RESEARCH.md's
// caveat and the task that produced this package both note that a golden-
// master test against a real machine is a separate, later step (Max has a
// real Gaggiuino to test against, but network access to it is not available
// in this environment). See cmd/gaggiuino-ws-probe (go/cmd/gaggiuino-ws-probe)
// for a small CLI this package ships specifically so that later step is a
// `go run` away instead of a from-scratch tool: point it at a real
// machine's ws:// URL and it dumps every decoded frame (with its raw hex)
// for exactly this kind of manual verification.
//
// # What's deliberately not modeled
//
// GaggiaSettingsDto (the REST-only settings payload) is not part of this
// package, matching lib/gaggiuino-proto.js's own header comment: the
// settings proxy (go/internal/machines's settings handlers) uses plain
// JSON over REST, not this binary protocol, and is treated as opaque JSON
// end-to-end specifically so the machine's inconsistent bool-as-string
// quirk (some settings fields are JSON `"true"`/`"false"` strings, not
// real JSON booleans — see go/internal/machines/doc.go) passes through
// byte-identical rather than being normalized away by a typed struct.
package proto
