// A real backup was exported with the "API token & MQTT login" checkbox
// checked and a passphrase entered, yet the resulting file had no `secrets`
// block and `sections` didn't list "secrets" at all — reported by Max
// against a live GLP DEV export.
//
// Root cause: public-src/components/backup-modal.js's checkedSections()
// collects every `.backup-section-cb` element's `value`. The six regular
// section checkboxes are generated by renderSectionCheckboxes() with both
// attributes set correctly, but the secrets checkbox is static markup in
// index.html and was missing both `class="backup-section-cb"` and
// `value="secrets"` — so it was silently invisible to checkedSections()
// regardless of whether the user checked it. The passphrase itself *was*
// sent, and the backend correctly computed the encrypted secrets block, but
// then correctly dropped it again because 'secrets' was never in the
// requested `sections` array. Every layer behaved "correctly" given its
// input; only the checkbox's own markup was wrong.
//
// A behavioral test through the full modal would need a fairly large fake
// DOM harness (see test/autocomplete.test.js's precedent) for marginal
// extra coverage over pinning the actual markup defect directly, so this
// asserts the two attributes checkedSections() depends on are present on
// the one checkbox that isn't generated by JS.
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(__dirname, '../public-src/index.html'), 'utf8');

function extractTag(id) {
    const m = html.match(new RegExp(`<input[^>]*\\bid="${id}"[^>]*>`));
    return m ? m[0] : null;
}

describe('backup modal: secrets checkbox markup', () => {
    it('is present in index.html', () => {
        expect(extractTag('backupSecretsCb')).not.toBeNull();
    });

    it('carries class="backup-section-cb", the attribute checkedSections() (backup-modal.js) selects on', () => {
        const tag = extractTag('backupSecretsCb');
        expect(tag).toMatch(/class="[^"]*\bbackup-section-cb\b[^"]*"/);
    });

    it('carries value="secrets", matching the "secrets" section key routes/backup.js expects', () => {
        const tag = extractTag('backupSecretsCb');
        expect(tag).toMatch(/value="secrets"/);
    });
});

describe('backup modal: progress row markup (#960)', () => {
    it('has a #backupModalProgress element inside the #backupModal block', () => {
        const modalBlock = html.slice(html.indexOf('id="backupModal"'), html.indexOf('<script type="module"'));
        expect(modalBlock).toContain('id="backupModalProgress"');
    });

    it('the progress row contains a .sync-progress-fill child (reuses the shot-import bar styles)', () => {
        const m = html.match(/<div id="backupModalProgress"[\s\S]*?<\/div>\s*<\/div>/);
        expect(m).not.toBeNull();
        expect(m[0]).toContain('sync-progress-fill');
        expect(m[0]).toContain('id="backupModalProgressLabel"');
    });
});
